# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vue2 project CI deploy to http://124.70.83.234:9000

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - name: 获取项目
      uses: actions/checkout@v3
      with:
          persist-credentials: false
    - name: 依赖下载代码打包
      run: |
        git pull
        yarn
        yarn build
    - name: 代码发布
      uses: cross-the-world/scp-pipeline@master
      with:
       host: ${{ secrets.HW_HOST }}
       user: ${{ secrets.HW_USERNAME }}
       pass: ${{ secrets.HW_PASSWORD }}
       connect_timeout: 10s
       local: "dist/*"
       remote: "/root/www/vue2-project/dist"

